title: matcalc
email: ongsp@ucsd.edu
description: >- # this means to ignore newlines until "baseurl:"
  MatCalc is a Python library for calculating materials properties from the potential energy surface (PES).
url: "http://materialsvirtuallab.github.io/matcalc/"
# twitter_username: matcalc
github_username: materialsvirtuallab

# Build settings
remote_theme: just-the-docs/just-the-docs

favicon_ico: /assets/favicon.png

aux_links:
  API docs: https://materialsvirtuallab.github.io/matcalc/matcalc.html
  GitHub: https://github.com/materialsvirtuallab/matcalc
  Issues: https://github.com/materialsvirtuallab/matcalc/issues
  Materials Virtual Lab: https://materialsvirtuallab.org

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

# Split pages into sections that can be searched individually
# Supports 1 - 6, default: 2
search.heading_level: 6

kramdown:
  toc_levels: 1..3
