name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install uv with python version.
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Install dependencies
        run: |
          uv venv
          uv pip install dgl -f https://data.dgl.ai/wheels/torch-2.4/repo.html
          uv sync --group lint --system

      - name: ruff
        run: |
          ruff --version
          ruff check src
          ruff format src --check

      - name: mypy
        run: |
          uv run mypy --version
          uv run rm -rf .mypy_cache
          uv run mypy -p matcalc
