name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install dgl==2.4.0 -f https://data.dgl.ai/wheels/torch-2.4/repo.html
          pip install -e .
          pip install ruff mypy

      - name: ruff
        run: |
          ruff --version
          ruff check src
          ruff format src --check

      - name: mypy
        run: |
          mypy --version
          rm -rf .mypy_cache
          mypy -p matcalc
