name: Testing

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      task:
        type: choice
        options: [tests, release]
        default: tests
        description: Only run tests or release a new version to PyPI after tests pass.

jobs:
  test:
    # run test.yml first to ensure that the test suite is passing
    uses: ./.github/workflows/testing.yml

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        name: Install Python
        with:
          python-version: "3.11"
      - run: python -m pip install build
      - name: Build sdist
        run: |
          python -m build --sdist
          python -m build --wheel
      - uses: actions/upload-artifact@v4
        with:
          path: dist/*.*

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      # For pypi trusted publishing
      id-token: write
    steps:
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifact
          path: dist
      - name: Publish to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
          verbose: true
