name: Release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      task:
        type: choice
        options: [release]
        default: release
        description: Trigger a release manually.

permissions:
  contents: read

jobs:
  test:
    # run test.yml first to ensure that the test suite is passing
    uses: ./.github/workflows/test.yml

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install dgl -f https://data.dgl.ai/wheels/torch-2.4/repo.html
          pip install -e .
          pip install ruff mypy

      - uses: actions/upload-artifact@v4
        with:
          path: dist/*.*

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      # For pypi trusted publishing
      id-token: write
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifact
          path: dist
      - name: Publish to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
          verbose: true
