name: Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      task:
        type: choice
        options: [tests, release]
        default: tests
        description: Only run tests or release a new version to PyPI after tests pass.
  workflow_call: # make this workflow reusable by release.yml

jobs:
  test:
    strategy:
      max-parallel: 20
      matrix:
        python-version: ["3.10"]

    runs-on: ubuntu-latest
    env:
      PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: python
      PMG_MAPI_KEY: ${{ secrets.PMG_MAPI_KEY }}

    steps:
      - uses: actions/checkout@v4
      - name: Install uv with python version.
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Install dependencies
        run: |
          uv sync
      - name: pytest
        run: |
          uv run pytest --cov=matcalc tests --color=yes
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
