name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      task:
        type: choice
        options: [tests, release]
        default: tests
        description: Only run tests or release a new version to PyPI after tests pass.
  workflow_call: # make this workflow reusable by release.yml

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: python
      PMG_MAPI_KEY: ${{ secrets.PMG_MAPI_KEY }}

    steps:
      - uses: actions/checkout@v4
      - name: Install uv.
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Install dependencies
        run: uv sync
      - name: pytest
        run: |
          uv run pytest --cov=matcalc tests --color=yes
          uv run codecovcli --verbose upload-process --disable-search --fail-on-error -t ${{ secrets.CODECOV_TOKEN }} -n 'service'-${{ github.run_id }} -F service -f coverage-service.xml
