name: Test-Notebooks

on:
  push:
    branches: [main]
    paths: ["examples/*.ipynb"]
  pull_request:
    branches: [main]
    paths: ["examples/*.ipynb"]
  release: # This workflow is only ran on releases.
    types: [published]
  workflow_call: # make this workflow reusable by release.yml
  workflow_dispatch:
    inputs:
      task:
        type: choice
        options: [test]
        default: test
        description: Run notebook tests.

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: python
      PMG_MAPI_KEY: ${{ secrets.PMG_MAPI_KEY }}

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          pip install dgl -f https://data.dgl.ai/wheels/torch-2.4/repo.html
          pip install -e '.[ci]'

      - name: Execute all notebook examples
        # Ensures that all notebooks are still functioning as intended.
        run: |
          pytest --nbmake --nbmake-timeout=2000 examples/*.ipynb
