name: Test

on:
  push:
    branches: [main,docker]
  workflow_dispatch:
    inputs:
      task:
        type: choice
        options: [test]
        default: test
        description: Trigger test manually.
  workflow_call: # make this workflow reusable by release.yml

jobs:
  test:
    runs-on: ubuntu-24.04-arm
    container:
      image: docker.io/materialsvirtuallab/lammps:latest-ml
    env:
      PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: python
      PMG_MAPI_KEY: ${{ secrets.PMG_MAPI_KEY }}

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: uv sync --group test-models
      - name: pytest
        run: uv run pytest --cov=matcalc --cov-report=xml tests --color=yes
