name: Test-LAMMPS

on:
  push:
    branches: [main,docker]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      task:
        type: choice
        options: [test]
        default: test
        description: Trigger test manually.
  workflow_call: # make this workflow reusable by release.yml

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: python
      PMG_MAPI_KEY: ${{ secrets.PMG_MAPI_KEY }}

    steps:
      - uses: actions/checkout@v4
      - name: Install uv.
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Install LAMMPS
        run: |
          uv run git clone https://github.com/advancesoftcorp/lammps.git
          mkdir -p lammps/build-serial
          cd lammps/build-serial
          cmake -C ../cmake/presets/basic.cmake -D BUILD_SHARED_LIBS=on -D LAMMPS_EXCEPTIONS=on -D PKG_PYTHON=on -D PKG_ML-GNNP=on -D PKG_EXTRA-COMPUTE=on -D PKG_EXTRA-FIX=on -D PKG_MANYBODY=on -D PKG_EXTRA-DUMP=on -D PKG_MOLECULE=on ../cmake
          make -j 8
          make install
      - name: Install dependencies
        run: uv sync --group test-models
      - name: pytest
        run: uv run pytest --cov=matcalc --cov-report=xml tests --color=yes
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
